
@baseUrl = http://localhost:5000/api
# Esta variable guardará el token después de un login exitoso.
@token =  


# 1. LOGIN (Para obtener el token)
# REGISTRO DE BARBERO (para desarrollo)
POST {{baseUrl}}/auth/register-barbero
Content-Type: application/json

{
    "nombre": "test",
    "email": "test@barberia.com",
    "password": "admin",
    "telefono": "722781744"
}
### Login de Barbero (Éxito)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@barberia.com",
    "password": "admin"
}



# Obtener Perfil de Barbero (CON TOKEN - Debería funcionar)
GET {{baseUrl}}/barberos/perfil
Authorization: Bearer {{token}}



# Obtener Perfil de Barbero (SIN TOKEN - Debería fallar)
GET {{baseUrl}}/barberos/perfil

# Obtener todos los barberos (Público)
GET {{baseUrl}}/barberos

# Obtener todos los servicios (Público)
GET {{baseUrl}}/servicios

